In [3]:
import pandas as pd
import json

In [2]:
df = pd.read_json("datos.json")
df.head()

               empresa                                          empleados
0  Ingeniero REC Store  {'nombre': 'Ana', 'puesto': 'Analista de Datos...
1  Ingeniero REC Store  {'nombre': 'Luis', 'puesto': 'Data Engineer', ...
2  Ingeniero REC Store  {'nombre': 'Maria', 'puesto': 'Analista BI', '...

In [5]:
with open("datos.json", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data["empleados"])
df.head()

  nombre             puesto     contacto.email contacto.ciudad
0    Ana  Analista de Datos    ana@empresa.com        Arequipa
1   Luis      Data Engineer   luis@empresa.com            Lima
2  Maria        Analista BI  maria@empresa.com           Cusco